#!/bin/bash

# bash_aliases

# Other aliases
alias e="exit"

# Aliases for git
alias gpu='git push -u'
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gbd='git branch -d '
alias gc='git commit'
alias gcm='git commit -m '
alias gcam='git commit -am '
alias gd='git diff'
alias go='git checkout '
alias gob='git checkout -b'
alias gl='git log --graph --abbrev-commit --decorate --date=relative --format=format:"%C(bold blue)%h%C(reset) -%C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)" --all'
alias gps='git push'
alias gpl='git pull'
alias gpfp='git pull && git fetch -p'

# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"
alias -- -="cd -"

# List dir contents aliases
# ref: http://ss64.com/osx/ls.html
# Long form no user group, color
alias l="ls -oG"
# Order by last modified, long form no user group, color
alias lt="ls -toG"
# List all except . and ..., color, mark file types, long form no user group, file size
alias la="ls -AGFoh"
# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AGFoth"

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

# Run phpcs with Symfony2 code style
alias check="phpcs --standard=Symfony2 "
alias fix="phpcbf --standard=Symfony2 "
